// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBF907lmS_r7xRid7q5KuM8Pjw27rcpfs',
    appId: '1:1065975608462:web:55434d1af060ba98d5c5df',
    messagingSenderId: '1065975608462',
    projectId: 'aptka-db',
    authDomain: 'aptka-db.firebaseapp.com',
    storageBucket: 'aptka-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo3nHwVtsB6nhqE4evEo0iZPUx-Eby6Hk',
    appId: '1:1065975608462:android:0821d87590c103f7d5c5df',
    messagingSenderId: '1065975608462',
    projectId: 'aptka-db',
    storageBucket: 'aptka-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkpJRrRRyrTdlDMzpvq0rO3TIHnCRO31U',
    appId: '1:1065975608462:ios:8f09ecd32de635dad5c5df',
    messagingSenderId: '1065975608462',
    projectId: 'aptka-db',
    storageBucket: 'aptka-db.firebasestorage.app',
    iosBundleId: 'com.example.aptka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkpJRrRRyrTdlDMzpvq0rO3TIHnCRO31U',
    appId: '1:1065975608462:ios:8f09ecd32de635dad5c5df',
    messagingSenderId: '1065975608462',
    projectId: 'aptka-db',
    storageBucket: 'aptka-db.firebasestorage.app',
    iosBundleId: 'com.example.aptka',
  );
}
